### ISSUE TITLE
IndexError: list index out of range`

### ISSUE THREAD

**Issue by vkutepov** [spaceone-dev/grpc_requests#22]
**Describe the bug**
I get this error when I create a client

`Traceback (most recent call last):
  File "/Users/vkutepov/response-differ/grpc_test.py", line 14, in <module>
    client = Client.get_by_endpoint('product-service.ps.stg.s.o3.ru:82')
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/grpc_requests/client.py", line 49, in get_by_endpoint
    _cached_clients[endpoint] = cls(endpoint, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/grpc_requests/client.py", line 149, in __init__
    self.register_all_service()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/grpc_requests/client.py", line 247, in register_all_service
    self.register_service(service)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/grpc_requests/client.py", line 240, in register_service
    self._register_file_descriptor(file_descriptor)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/grpc_requests/client.py", line 185, in _register_file_descriptor
    dep_desc = self._get_file_descriptor_by_name(dep_file_name)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/grpc_requests/client.py", line 170, in _get_file_descriptor_by_name
    proto = result.file_descriptor_response.file_descriptor_proto[0]
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/google/protobuf/internal/containers.py", line 209, in __getitem__
    return self._values[key]
IndexError: list index out of range`

**To Reproduce**
1. client = Client.get_by_endpoint("localhost:82")

**Desktop (please complete the following information):**
 - grpc_requests = "^0.0.10"

**Comment by wesky93** [comment]
@vkutepov  Could you please share some information about the proto file used on the local server or the client code where the error occurred?

**Comment by SaladBreaker** [comment]
This error seems to still be present:
I have a system and I need to send requests to a grpc server. On the CLI I can do:
```
grpc-client-cli host.default.svc.cluster.local:50055
```

but from python:
```
from grpc_requests import Client
client = Client.get_by_endpoint("host.default.svc.cluster.local:50055")
```
Outputs:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/app/.venv/lib/python3.9/site-packages/grpc_requests/client.py", line 82, in get_by_endpoint
    _cached_clients[endpoint] = cls(endpoint, **kwargs)
  File "/app/.venv/lib/python3.9/site-packages/grpc_requests/client.py", line 320, in __init__
    self.register_all_service()
  File "/app/.venv/lib/python3.9/site-packages/grpc_requests/client.py", line 231, in register_all_service
    self.register_service(service)
  File "/app/.venv/lib/python3.9/site-packages/grpc_requests/client.py", line 381, in register_service
    super(ReflectionClient, self).register_service(service_name)
  File "/app/.venv/lib/python3.9/site-packages/grpc_requests/client.py", line 226, in register_service
    self._service_methods_meta[service_name] = self._register_methods(svc_desc)
  File "/app/.venv/lib/python3.9/site-packages/grpc_requests/client.py", line 198, in _register_methods
    service_descriptor.CopyToProto(svc_desc_proto)
  File "/app/.venv/lib/python3.9/site-packages/google/protobuf/descriptor.py", line 865, in CopyToProto
    super(ServiceDescriptor, self).CopyToProto(proto)
  File "/app/.venv/lib/python3.9/site-packages/google/protobuf/descriptor.py", line 238, in CopyToProto
    raise Error('Descriptor does not contain serialization.')
google.protobuf.descriptor.Error: Descriptor does not contain serialization.
```

**Comment by wesky93** [comment]
@SaladBreaker thank you so much!
